FROM maven:3.9.3-eclipse-temurin-17
WORKDIR /app

COPY pom.xml .
RUN mvn dependency:go-offline -B

COPY src ./src
EXPOSE 8080

ENTRYPOINT ["mvn", "spring-boot:run", "-Duser.timezone=Asia/Kolkata"]