/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as ProtectedRouteRouteImport } from "./routes/_protected/route";
import { Route as AuthRouteRouteImport } from "./routes/_auth/route";
import { Route as ProtectedIndexRouteImport } from "./routes/_protected/index";
import { Route as AuthSignupRouteImport } from "./routes/_auth/signup";
import { Route as AuthLoginRouteImport } from "./routes/_auth/login";
import { Route as AuthForgotPasswordRouteImport } from "./routes/_auth/forgot-password";

const ProtectedRouteRoute = ProtectedRouteRouteImport.update({
  id: "/_protected",
  getParentRoute: () => rootRouteImport,
} as any);
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: "/_auth",
  getParentRoute: () => rootRouteImport,
} as any);
const ProtectedIndexRoute = ProtectedIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => ProtectedRouteRoute,
} as any);
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: "/signup",
  path: "/signup",
  getParentRoute: () => AuthRouteRoute,
} as any);
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => AuthRouteRoute,
} as any);
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: "/forgot-password",
  path: "/forgot-password",
  getParentRoute: () => AuthRouteRoute,
} as any);

export interface FileRoutesByFullPath {
  "/forgot-password": typeof AuthForgotPasswordRoute;
  "/login": typeof AuthLoginRoute;
  "/signup": typeof AuthSignupRoute;
  "/": typeof ProtectedIndexRoute;
}
export interface FileRoutesByTo {
  "/forgot-password": typeof AuthForgotPasswordRoute;
  "/login": typeof AuthLoginRoute;
  "/signup": typeof AuthSignupRoute;
  "/": typeof ProtectedIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/_auth": typeof AuthRouteRouteWithChildren;
  "/_protected": typeof ProtectedRouteRouteWithChildren;
  "/_auth/forgot-password": typeof AuthForgotPasswordRoute;
  "/_auth/login": typeof AuthLoginRoute;
  "/_auth/signup": typeof AuthSignupRoute;
  "/_protected/": typeof ProtectedIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: "/forgot-password" | "/login" | "/signup" | "/";
  fileRoutesByTo: FileRoutesByTo;
  to: "/forgot-password" | "/login" | "/signup" | "/";
  id:
    | "__root__"
    | "/_auth"
    | "/_protected"
    | "/_auth/forgot-password"
    | "/_auth/login"
    | "/_auth/signup"
    | "/_protected/";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  AuthRouteRoute: typeof AuthRouteRouteWithChildren;
  ProtectedRouteRoute: typeof ProtectedRouteRouteWithChildren;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/_protected": {
      id: "/_protected";
      path: "";
      fullPath: "";
      preLoaderRoute: typeof ProtectedRouteRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_auth": {
      id: "/_auth";
      path: "";
      fullPath: "";
      preLoaderRoute: typeof AuthRouteRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_protected/": {
      id: "/_protected/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof ProtectedIndexRouteImport;
      parentRoute: typeof ProtectedRouteRoute;
    };
    "/_auth/signup": {
      id: "/_auth/signup";
      path: "/signup";
      fullPath: "/signup";
      preLoaderRoute: typeof AuthSignupRouteImport;
      parentRoute: typeof AuthRouteRoute;
    };
    "/_auth/login": {
      id: "/_auth/login";
      path: "/login";
      fullPath: "/login";
      preLoaderRoute: typeof AuthLoginRouteImport;
      parentRoute: typeof AuthRouteRoute;
    };
    "/_auth/forgot-password": {
      id: "/_auth/forgot-password";
      path: "/forgot-password";
      fullPath: "/forgot-password";
      preLoaderRoute: typeof AuthForgotPasswordRouteImport;
      parentRoute: typeof AuthRouteRoute;
    };
  }
}

interface AuthRouteRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute;
  AuthLoginRoute: typeof AuthLoginRoute;
  AuthSignupRoute: typeof AuthSignupRoute;
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
};

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(AuthRouteRouteChildren);

interface ProtectedRouteRouteChildren {
  ProtectedIndexRoute: typeof ProtectedIndexRoute;
}

const ProtectedRouteRouteChildren: ProtectedRouteRouteChildren = {
  ProtectedIndexRoute: ProtectedIndexRoute,
};

const ProtectedRouteRouteWithChildren = ProtectedRouteRoute._addFileChildren(
  ProtectedRouteRouteChildren
);

const rootRouteChildren: RootRouteChildren = {
  AuthRouteRoute: AuthRouteRouteWithChildren,
  ProtectedRouteRoute: ProtectedRouteRouteWithChildren,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
