server:
  servlet:
    context-path: /api

frontend:
  url:
    dev: http://localhost:5173
    prod: https://sca.void9.space

logging:
  level:
    org.apache.kafka: OFF
    org.springframework.kafka: OFF

spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:postgresql://postgres:5432/spring-sca
    username: raghav
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  servlet:
    multipart:
      max-file-size: 15MB
      max-request-size: 15MB
  data:
    redis:
      host: redis
      port: 6379
  kafka:
    bootstrap-servers: kafka:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: spring-kafka-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
  mail:
    host: smtp.gmail.com
    port: 587
    username: raghavbhagat32@gmail.com
    password: jgdl ubtp yyuf eeqj
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
  security.oauth2.client.registration:
    google:
      client-id: 987358419549-7hepeun9c7qr28f0o9peo26be7vhck7b.apps.googleusercontent.com
      client-secret: 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
      redirect-uri: "http://localhost:8080/api/login/oauth2/code/google"
    github:
      client-id: Iv23li5eofXL06XSatYF
      client-secret: e043ce44d76ffc281da474f1961b08d2b37cde47
      redirect-uri: "http://localhost:8080/api/login/oauth2/code/github"
  session:
    store-type: redis

jwt:
  secret: dshbgfusdvfgesdfhlgbhljesdbgfhjkledbsghjklbedlhjkfbgbhjlearsjgf
  expiration: 1296000000 # JWT uses time in milliseconds

cookie:
  expiration: 12960000 # Cookie uses time in seconds

cloudinary:
  cloud-name: dkyxlrmcg
  api-key: 228997985731528
  api-secret: v7ICBGN1ULXJ59XNwCUYzg7X55E
