server:
  servlet:
    context-path: /api

frontend:
  url:
    dev: http://localhost:5173
    prod: http://localhost:3000

spring:
  devtools:
    restart:
      enabled: true
      trigger-file: .restart-trigger
  datasource:
    url: jdbc:postgresql://postgres:5432/spring-sca
    username: raghav
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  servlet:
    multipart:
      max-file-size: 15MB
      max-request-size: 15MB
  data:
    redis:
      host: redis
      port: 6379
  kafka:
    bootstrap-servers: kafka:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: spring-kafka-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"

jwt:
  secret: dshbgfusdvfgesdfhlgbhljesdbgfhjkledbsghjklbedlhjkfbgbhjlearsjgf
  expiration: 1296000000 # JWT uses time in milliseconds

cookie:
  expiration: 12960000 # Cookie uses time in seconds

cloudinary:
  cloud-name: dkyxlrmcg
  api-key: 228997985731528
  api-secret: v7ICBGN1ULXJ59XNwCUYzg7X55E
