server:
  servlet:
    context-path: /api

frontend:
  url:
    dev: http://localhost:5173
    prod: http://localhost:3000

spring:
  datasource:
    url: jdbc:postgresql://localhost:5430/spring-auth
    username: raghav
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  servlet:
    multipart:
      max-file-size: 15MB
      max-request-size: 15MB

jwt:
  secret: dshbgfusdvfgesdfhlgbhljesdbgfhjkledbsghjklbedlhjkfbgbhjlearsjgf
  expiration: 86400000 # JWT uses time in milliseconds (1 day = 86400000 ms)

cookie:
  expiration: 86400 # Cookie uses time in seconds (1 day = 86400 seconds)

cloudinary:
  cloud-name: dkyxlrmcg
  api-key: 228997985731528
  api-secret: v7ICBGN1ULXJ59XNwCUYzg7X55E